SMF =
{
  INSTANCE_ID = 0;
  PID_DIRECTORY = "/var/run";
  SMF_NAME = "OAI-SMF-Stadium";

  INTERFACES:
  {
    N4:
    {
      INTERFACE_NAME = "eth0";
      IPV4_ADDRESS   = "192.168.70.133";
    };
    SBI:
    {
      INTERFACE_NAME = "eth0";
      IPV4_ADDRESS   = "192.168.70.133";
      PORT           = 80;
      HTTP2_PORT     = 8080;
      API_VERSION    = "v1";
    };
  };

  SUPPORT_FEATURES:
  {
    NF_REGISTRATION             = "yes";
    NRF_SELECTION               = "yes";
    EXTERNAL_NRF                = "yes";
    USE_LOCAL_SUBSCRIPTION_INFO = "yes";
    USE_FQDN_DNS                = "no";
    USE_HTTP2                   = "no";
  };

  UPF_LIST = (
    {
      IPV4_ADDRESS = "192.168.70.140";
      FQDN         = "oai-upf-mec";
      NWI_LIST     = ( { NWI = "internet.oai.org"; } );
      UPF_PORT     = 8805;
    },
    {
      IPV4_ADDRESS = "192.168.70.141";
      FQDN         = "oai-upf-cc";
      NWI_LIST     = ( { NWI = "internet.oai.org"; } );
      UPF_PORT     = 8805;
    }
  );

  DNN_LIST = (
    {
      DNN_NI                       = "oai";
      DEFAULT_DNS_IPV4_ADDRESS     = "8.8.8.8";
      DEFAULT_DNS_SEC_IPV4_ADDRESS = "8.8.4.4";
      PDU_SESSION_TYPE             = "IPV4";
      IPV4_POOL                    = "12.1.1.0/24";
      IPV4_UE_MTU                  = 1500;
    },
    {
      DNN_NI                       = "oai2";
      DEFAULT_DNS_IPV4_ADDRESS     = "8.8.8.8";
      DEFAULT_DNS_SEC_IPV4_ADDRESS = "8.8.4.4";
      PDU_SESSION_TYPE             = "IPV4";
      IPV4_POOL                    = "12.2.1.0/24";
      IPV4_UE_MTU                  = 1500;
    }
  );

  LOCAL_SUBSCRIPTION_INFOS = (
    {
      NSSAI_SST = 1;
      NSSAI_SD  = "0xFFFFFF";
      DNN       = "oai";
    },
    {
      NSSAI_SST = 2;
      NSSAI_SD  = "0xFFFFFF";
      DNN       = "oai2";
    }
  );

  NRF:
  {
    IPV4_ADDRESS = "192.168.70.130";
    PORT         = 80;
    API_VERSION  = "v1";
    FQDN         = "oai-nrf";
  };

  AMF:
  {
    IPV4_ADDRESS = "192.168.70.132";
    PORT         = 80;
    API_VERSION  = "v1";
    FQDN         = "oai-amf";
  };
};
