database:
  connection_timeout: 300
  database_name: oai_db
  generate_random: true
  host: mysql
  password: test
  type: mysql
  user: test
dnns:
- dnn: oai
  ipv4_subnet: 12.1.1.0/24
  pdu_session_type: IPV4
- dnn: oai2
  ipv4_subnet: 12.2.1.0/24
  pdu_session_type: IPV4
http_version: 2
log_level:
  general: debug
nfs:
  upf:
    host: oai-upf-mec
    n3:
      interface_name: eth0
      port: 2152
    n4:
      interface_name: eth0
      port: 8805
    n6:
      interface_name: eth0
    n9:
      interface_name: eth0
      port: 2152
    sbi:
      api_version: v1
      interface_name: eth0
      port: 8080
register_nf:
  general: 'yes'
snssais:
- &id001
  sd: FFFFFF
  sst: 1
- &id002
  sd: FFFFFF
  sst: 2
upf:
  remote_n6_gw: localhost
  smfs:
  - host: oai-smf
  support_features:
    enable_bpf_datapath: false
    enable_snat: true
  upf_info:
    capacity: 100
    priority: 50
    sNssaiUpfInfoList:
    - dnnUpfInfoList:
      - dnn: oai
      - dnn: oai2
      sNssai: *id001
    - dnnUpfInfoList:
      - dnn: oai
      - dnn: oai2
      sNssai: *id002
